INSERT INTO [dbo].[image] ([path],[caption])
VALUES
('18px-Flag_of_Nepal.svg.png','Federale Democratische Republiek Nepal'),
('24px-Flag_of_Switzerland_(Pantone).svg.png','Zwitserse Bondsstaat'),
('24px-Flag_of_the_Vatican_City.svg.png','Staat Vaticaanstad'),
('30px-Flag_of_Afghanistan.svg.png','Islamitische Republiek Afghanistan'),
('30px-Flag_of_Albania.svg.png','Republiek Albanië'),
('30px-Flag_of_Algeria.svg.png','Democratische Volksrepubliek Algerije'),
('30px-Flag_of_Andorra.svg.png','Vorstendom Andorra'),
('30px-Flag_of_Angola.svg.png','Republiek Angola'),
('30px-Flag_of_Antigua_and_Barbuda.svg.png','Antigua en Barbuda'),
('30px-Flag_of_Argentina.svg.png','Argentijnse Republiek'),
('30px-Flag_of_Armenia.svg.png','Republiek Armenië'),
('30px-Flag_of_Australia.svg.png','Gemenebest Australië'),
('30px-Flag_of_Austria.svg.png','Republiek Oostenrijk'),
('30px-Flag_of_Azerbaijan.svg.png','Republiek Azerbeidzjan'),
('30px-Flag_of_Bahrain.svg.png','Koninkrijk Bahrein'),
('30px-Flag_of_Bangladesh.svg.png','Volksrepubliek Bangladesh'),
('30px-Flag_of_Barbados.svg.png','Barbados'),
('30px-Flag_of_Belarus.svg.png','Republiek Belarus'),
('30px-Flag_of_Belgium_(civil).svg.png','Koninkrijk België'),
('30px-Flag_of_Belize.svg.png','Belize'),
('30px-Flag_of_Benin.svg.png','Republiek Benin'),
('30px-Flag_of_Bhutan.svg.png','Koninkrijk Bhutan'),
('30px-Flag_of_Bolivia.svg.png','Plurinationale Staat Bolivia'),
('30px-Flag_of_Bosnia_and_Herzegovina.svg.png','Bosnië en Herzegovina'),
('30px-Flag_of_Botswana.svg.png','Republiek Botswana'),
('30px-Flag_of_Brazil.svg.png','Federale Republiek Brazilië'),
('30px-Flag_of_Brunei.svg.png','Staat Brunei Darussalam'),
('30px-Flag_of_Bulgaria.svg.png','Republiek Bulgarije'),
('30px-Flag_of_Burkina_Faso.svg.png','Burkina Faso'),
('30px-Flag_of_Burundi.svg.png','Republiek Burundi'),
('30px-Flag_of_Cambodia.svg.png','Koninkrijk Cambodja'),
('30px-Flag_of_Cameroon.svg.png','Republiek Kameroen'),
('30px-Flag_of_Canada.svg.png','Canada'),
('30px-Flag_of_Cape_Verde.svg.png','Republiek Kaapverdië'),
('30px-Flag_of_Chad.svg.png','Republiek Tsjaad'),
('30px-Flag_of_Chile.svg.png','Republiek Chili'),
('30px-Flag_of_Colombia.svg.png','Republiek Colombia'),
('30px-Flag_of_Costa_Rica_(state).svg.png','Republiek Costa Rica'),
('30px-Flag_of_Croatia.svg.png','Republiek Kroatië'),
('30px-Flag_of_Cuba.svg.png','Republiek Cuba'),
('30px-Flag_of_Cyprus.svg.png','Republiek Cyprus'),
('30px-Flag_of_Côte_d''Ivoire.svg.png','Republiek Ivoorkust'),
('30px-Flag_of_Denmark.svg.png','Koninkrijk Denemarken'),
('30px-Flag_of_Djibouti.svg.png','Republiek Djibouti'),
('30px-Flag_of_Dominica.svg.png','Gemenebest Dominica'),
('30px-Flag_of_East_Timor.svg.png','Democratische Republiek Oost-Timor'),
('30px-Flag_of_Ecuador.svg.png','Republiek Ecuador'),
('30px-Flag_of_Egypt.svg.png','Arabische Republiek Egypte'),
('30px-Flag_of_El_Salvador.svg.png','Republiek El Salvador'),
('30px-Flag_of_Equatorial_Guinea.svg.png','Republiek Equatoriaal-Guinea'),
('30px-Flag_of_Estonia.svg.png','Republiek Estland'),
('30px-Flag_of_Ethiopia.svg.png','Federale Democratische Republiek Ethiopië'),
('30px-Flag_of_Fiji.svg.png','Republiek Fiji'),
('30px-Flag_of_Finland.svg.png','Republiek Finland'),
('30px-Flag_of_France.svg.png','Franse Republiek'),
('30px-Flag_of_Gabon.svg.png','Republiek Gabon'),
('30px-Flag_of_Georgia.svg.png','Georgië'),
('30px-Flag_of_Germany.svg.png','Bondsrepubliek Duitsland'),
('30px-Flag_of_Ghana.svg.png','Republiek Ghana'),
('30px-Flag_of_Greece.svg.png','Helleense Republiek'),
('30px-Flag_of_Grenada.svg.png','Grenada'),
('30px-Flag_of_Guatemala.svg.png','Republiek Guatemala'),
('30px-Flag_of_Guinea-Bissau.svg.png','Republiek Guinee-Bissau'),
('30px-Flag_of_Guinea.svg.png','Republiek Guinee'),
('30px-Flag_of_Guyana.svg.png','Coöperatieve Republiek Guyana'),
('30px-Flag_of_Haiti.svg.png','Republiek Haïti'),
('30px-Flag_of_Honduras.svg.png','Republiek Honduras'),
('30px-Flag_of_Hungary.svg.png','Hongarije'),
('30px-Flag_of_Iceland.svg.png','IJsland'),
('30px-Flag_of_India.svg.png','Republiek India'),
('30px-Flag_of_Indonesia.svg.png','Republiek Indonesië'),
('30px-Flag_of_Iran.svg.png','Islamitische Republiek Iran'),
('30px-Flag_of_Iraq.svg.png','Republiek Irak'),
('30px-Flag_of_Ireland.svg.png','Ierland'),
('30px-Flag_of_Israel.svg.png','Staat Israël'),
('30px-Flag_of_Italy.svg.png','Italiaanse Republiek'),
('30px-Flag_of_Jamaica.svg.png','Jamaica'),
('30px-Flag_of_Japan.svg.png','Japan'),
('30px-Flag_of_Jordan.svg.png','Hasjemitisch Koninkrijk Jordanië'),
('30px-Flag_of_Kazakhstan.svg.png','Republiek Kazachstan'),
('30px-Flag_of_Kenya.svg.png','Republiek Kenia'),
('30px-Flag_of_Kiribati.svg.png','Republiek Kiribati'),
('30px-Flag_of_Kosovo.svg.png','Republiek Kosovo'),
('30px-Flag_of_Kuwait.svg.png','Staat Koeweit'),
('30px-Flag_of_Kyrgyzstan.svg.png','Kirgizische Republiek'),
('30px-Flag_of_Laos.svg.png','Democratische Volksrepubliek Laos'),
('30px-Flag_of_Latvia.svg.png','Republiek Letland'),
('30px-Flag_of_Lebanon.svg.png','Republiek Libanon'),
('30px-Flag_of_Lesotho.svg.png','Koninkrijk Leshoto'),
('30px-Flag_of_Liberia.svg.png','Republiek Liberia'),
('30px-Flag_of_Libya.svg.png','Staat Libië'),
('30px-Flag_of_Liechtenstein.svg.png','Vorstendom Liechtenstein'),
('30px-Flag_of_Lithuania.svg.png','Republiek Litouwen'),
('30px-Flag_of_Luxembourg.svg.png','Groothertogdom Luxemburg'),
('30px-Flag_of_Macedonia.svg.png','Republiek Macedonië'),
('30px-Flag_of_Madagascar.svg.png','Republiek Madagaskar'),
('30px-Flag_of_Malawi.svg.png','Republiek Malawi'),
('30px-Flag_of_Malaysia.svg.png','Maleisië'),
('30px-Flag_of_Maldives.svg.png','Republiek der Maldiven'),
('30px-Flag_of_Mali.svg.png','Republiek Mali'),
('30px-Flag_of_Malta.svg.png','Republiek Malta'),
('30px-Flag_of_Mauritania.svg.png','Islamitische Republiek Mauritanië'),
('30px-Flag_of_Mauritius.svg.png','Republiek Mauritius'),
('30px-Flag_of_Mexico.svg.png','Verenigde Mexicaanse Staten'),
('30px-Flag_of_Moldova.svg.png','Republiek Moldavië'),
('30px-Flag_of_Monaco.svg.png','Vorstendom Monaco'),
('30px-Flag_of_Mongolia.svg.png','Mongolië'),
('30px-Flag_of_Montenegro.svg.png','Montenegro'),
('30px-Flag_of_Morocco.svg.png','Koninkrijk Marokko'),
('30px-Flag_of_Mozambique.svg.png','Republiek Mozambique'),
('30px-Flag_of_Myanmar.svg.png','Republiek Unie van Myanmar'),
('30px-Flag_of_Namibia.svg.png','Republiek Namibië'),
('30px-Flag_of_Nauru.svg.png','Republiek Nauru'),
('30px-Flag_of_New_Zealand.svg.png','Nieuw-Zeeland'),
('30px-Flag_of_Nicaragua.svg.png','Republiek Nicaragua'),
('30px-Flag_of_Niger.svg.png','Republiek Niger'),
('30px-Flag_of_Nigeria.svg.png','Federale Republiek Nigeria'),
('30px-Flag_of_North_Korea.svg.png','Democratische Volksrepubliek Korea'),
('30px-Flag_of_Norway.svg.png','Koninkrijk Noorwegen'),
('30px-Flag_of_Oman.svg.png','Sultanaat Oman'),
('30px-Flag_of_Pakistan.svg.png','Islamitische Republiek Pakistan'),
('30px-Flag_of_Palau.svg.png','Republiek Palau'),
('30px-Flag_of_Palestine.svg.png','Staat Palestina'),
('30px-Flag_of_Panama.svg.png','Republiek Panama'),
('30px-Flag_of_Papua_New_Guinea.svg.png','Onafhankelijke Staat Papoea-Nieuw-Guinea'),
('30px-Flag_of_Paraguay.svg.png','Republiek Paraguay'),
('30px-Flag_of_Peru.svg.png','Republiek Peru'),
('30px-Flag_of_Poland.svg.png','Republiek Polen'),
('30px-Flag_of_Portugal.svg.png','Portugese Republiek'),
('30px-Flag_of_Qatar.svg.png','Staat Qatar'),
('30px-Flag_of_Romania.svg.png','Roemenië'),
('30px-Flag_of_Russia.svg.png','Russische Federatie'),
('30px-Flag_of_Rwanda.svg.png','Republiek Rwanda'),
('30px-Flag_of_Saint_Kitts_and_Nevis.svg.png','Federatie van Saint Kitts en Nevis'),
('30px-Flag_of_Saint_Lucia.svg.png','Saint Lucia'),
('30px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png','Saint Vincent en de Grenadines'),
('30px-Flag_of_Samoa.svg.png','Onafhankelijke Staat Samoa'),
('30px-Flag_of_San_Marino.svg.png','Republiek San Marino'),
('30px-Flag_of_Sao_Tome_and_Principe.svg.png','Democratische Republiek Sao Tomé en Principe'),
('30px-Flag_of_Saudi_Arabia.svg.png','Koninkrijk Saoedi-Arabië'),
('30px-Flag_of_Senegal.svg.png','Republiek Senegal'),
('30px-Flag_of_Serbia.svg.png','Republiek Servië'),
('30px-Flag_of_Seychelles.svg.png','Republiek der Seychellen'),
('30px-Flag_of_Sierra_Leone.svg.png','Republiek Sierra Leone'),
('30px-Flag_of_Singapore.svg.png','Republiek Singapore'),
('30px-Flag_of_Slovakia.svg.png','Slowaakse Republiek'),
('30px-Flag_of_Slovenia.svg.png','Republiek Slovenië'),
('30px-Flag_of_Somalia.svg.png','Federale Republiek Somalië'),
('30px-Flag_of_South_Africa.svg.png','Republiek Zuid-Afrika'),
('30px-Flag_of_South_Korea.svg.png','Republiek Korea'),
('30px-Flag_of_South_Sudan.svg.png','Republiek Zuid-Soedan'),
('30px-Flag_of_Spain.svg.png','Koninkrijk Spanje'),
('30px-Flag_of_Sri_Lanka.svg.png','Democratische Socialistische Republiek Sri Lanka'),
('30px-Flag_of_Sudan.svg.png','Republiek Soedan'),
('30px-Flag_of_Suriname.svg.png','Republiek Suriname'),
('30px-Flag_of_Swaziland.svg.png','Koninkrijk eSwatini'),
('30px-Flag_of_Sweden.svg.png','Koninkrijk Zweden'),
('30px-Flag_of_Syria.svg.png','Arabische Republiek Syrië'),
('30px-Flag_of_Tajikistan.svg.png','Republiek Tadzjikistan'),
('30px-Flag_of_Tanzania.svg.png','Verenigde Republiek Tanzania'),
('30px-Flag_of_Thailand.svg.png','Koninkrijk Thailand'),
('30px-Flag_of_the_Bahamas.svg.png','Gemenebest van de Bahama''s'),
('30px-Flag_of_the_Central_African_Republic.svg.png','Centraal-Afrikaanse Republiek'),
('30px-Flag_of_the_Comoros.svg.png','Unie der Comoren'),
('30px-Flag_of_the_Czech_Republic.svg.png','Tsjechische Republiek'),
('30px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png','Democratische Republiek Congo'),
('30px-Flag_of_the_Dominican_Republic.svg.png','Dominicaanse Republiek'),
('30px-Flag_of_the_Federated_States_of_Micronesia.svg.png','Federale Staten van Micronesia'),
('30px-Flag_of_The_Gambia.svg.png','Republiek Gambia'),
('30px-Flag_of_the_Marshall_Islands.svg.png','Republiek der Marshalleilanden'),
('30px-Flag_of_the_Netherlands.svg.png','Koninkrijk der Nederlanden'),
('30px-Flag_of_the_People''s_Republic_of_China.svg.png','Volksrepubliek China'),
('30px-Flag_of_the_Philippines.svg.png','Republiek der Filipijnen'),
('30px-Flag_of_the_Republic_of_the_Congo.svg.png','Republiek Congo'),
('30px-Flag_of_the_Solomon_Islands.svg.png','Salomonseilanden'),
('30px-Flag_of_the_United_Arab_Emirates.svg.png','Verenigde Arabische Emiraten (VAE)'),
('30px-Flag_of_the_United_Kingdom.svg.png','Verenigd Koninkrijk van Groot-Brittanië en Noord-Ierland'),
('30px-Flag_of_the_United_States.svg.png','Verenigde Staten van Amerika'),
('30px-Flag_of_Togo.svg.png','Republiek Togo'),
('30px-Flag_of_Tonga.svg.png','Koninkrijk Tonga'),
('30px-Flag_of_Trinidad_and_Tobago.svg.png','Republiek Trinidad en Tobago'),
('30px-Flag_of_Tunisia.svg.png','Republiek Tunesië'),
('30px-Flag_of_Turkey.svg.png','Republiek Turkije'),
('30px-Flag_of_Turkmenistan.svg.png','Turkmenistan'),
('30px-Flag_of_Tuvalu.svg.png','Tuvalu'),
('30px-Flag_of_Uganda.svg.png','Republiek Oeganda'),
('30px-Flag_of_Ukraine.svg.png','Oekraïne'),
('30px-Flag_of_Uruguay.svg.png','Republiek ten oosten van de Uruguay'),
('30px-Flag_of_Uzbekistan.svg.png','Republiek Oezbekistan'),
('30px-Flag_of_Vanuatu.svg.png','Republiek Vanuatu'),
('30px-Flag_of_Venezuela.svg.png','Bolivariaanse Republiek Venezuela'),
('30px-Flag_of_Vietnam.svg.png','Socialistische Republiek Vietnam'),
('30px-Flag_of_Yemen.svg.png','Republiek Jemen'),
('30px-Flag_of_Zambia.svg.png','Republiek Zambia'),
('30px-Flag_of_Zimbabwe.svg.png','Republiek Zimbabwe');